language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/hello/hello.ino
    - PLATFORMIO_CI_SRC=examples/breathe/breathe.ino
    - PLATFORMIO_CI_SRC=examples/simple_on/simple_on.ino
    - CPP_LINT_URL=https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py

install:
    - pip install -U platformio
    - wget -O cpplint "$CPP_LINT_URL" && chmod 755 cpplint

script:
    - ./cpplint --extensions=cpp,h,ino \
              $(find . -name "*\.cpp" -o -name "*\.h" -o -name "*\.ino") 
    - platformio ci --lib="src/" --board=uno --board=esp01

